tox-dev/tox-ini-fmt

.github/workflows/check.yml
.pre-commit-config.yaml
pyproject.toml
setup.cfg
src/tox_ini_fmt/__init__.py
src/tox_ini_fmt/__main__.py
src/tox_ini_fmt/cli.py
src/tox_ini_fmt/formatter.py
tests/test_cli.py
tests/test_formatter.py
tests/test_tox_ini_fmt.py
tox.ini

First batch of fixes

---

src/tox_ini_fmt/formatter/__init__.py
src/tox_ini_fmt/formatter/requires.py
src/tox_ini_fmt/formatter/test_env.py
src/tox_ini_fmt/formatter/tox_section.py
src/tox_ini_fmt/formatter/util.py
tests/formatter/test_requires.py
tests/formatter/test_test_env.py

Format testenvs

---

src/tox_ini_fmt/formatter/test_env.py
tests/formatter/test_test_env.py

Handle setenv and passenv

---

tox.ini

Self apply

---

.pre-commit-config.yaml
README.md
setup.cfg
tox.ini

Fix setup.cfg

---

.pre-commit-config.yaml
tox.ini

Eat our own dogfood

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
src/tox_ini_fmt/__main__.py
src/tox_ini_fmt/cli.py
src/tox_ini_fmt/formatter/__init__.py
src/tox_ini_fmt/formatter/section_order.py
src/tox_ini_fmt/formatter/tox_section.py
tests/formatter/test_section_order.py
tests/formatter/test_tox_section.py
tox.ini

Fix envlist ordering and add ability to pin

---

README.md

Resolves https://github.com/tox-dev/tox-ini-fmt/issues/27

Document what we do not do

---

CHANGELOG.md
src/tox_ini_fmt/formatter/test_env.py
tests/formatter/test_test_env.py

Resolves https://github.com/tox-dev/tox-ini-fmt/issues/21

Support -r and conditional markers in deps

---

setup.cfg

drop `pytest` as an `install_requirement`

---

.pre-commit-config.yaml
setup.cfg
tox.ini

Bump pre-commit

---

src/tox_ini_fmt/formatter/__init__.py
tests/test_main.py

Fixes #65
I'm not sure if setting this has unintended side effects on some other part of the code but it fixes the problem in #65.

Don't try to interpolate values in config

---

.pre-commit-config.yaml
src/tox_ini_fmt/cli.py
tests/test_cli.py
tests/test_tox_ini_fmt.py
tox.ini

Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>

Support windows, bump linters

---

.markdownlint.yaml
.pre-commit-config.yaml
.pre-commit-hooks.yaml
CHANGELOG.md
pyproject.toml
setup.py
src/tox_ini_fmt/formatter/test_env.py
tests/conftest.py
tests/formatter/test_line_endings.py
tests/formatter/test_requires.py
tests/formatter/test_section_order.py
tests/formatter/test_test_env.py
tests/formatter/test_tox_section.py
tests/test_cli.py
tests/test_main.py
tests/test_tox_ini_fmt.py
tox.ini

Use hatchling over setuptools and add type annotations to tests

---

src/tox_ini_fmt/formatter/test_env.py
tests/formatter/test_test_env.py

Support conditional markers in general on lists

---

src/tox_ini_fmt/formatter/test_env.py
src/tox_ini_fmt/formatter/tox_section.py
tests/formatter/test_test_env.py

Fix pytest ordered after pytest-cov

---

src/tox_ini_fmt/formatter/section_order.py
src/tox_ini_fmt/formatter/test_env.py
src/tox_ini_fmt/formatter/tox_section.py
src/tox_ini_fmt/formatter/util.py
tests/formatter/test_test_env.py
tests/formatter/test_tox_section.py
tox.ini

Order depends

---

pyproject.toml
src/tox_ini_fmt/__main__.py
src/tox_ini_fmt/formatter/__init__.py
src/tox_ini_fmt/formatter/requires.py
src/tox_ini_fmt/formatter/section_order.py
src/tox_ini_fmt/formatter/test_env.py
src/tox_ini_fmt/formatter/tox_section.py
src/tox_ini_fmt/formatter/util.py
tests/formatter/test_line_endings.py
tests/formatter/test_requires.py
tests/formatter/test_section_order.py
tests/formatter/test_test_env.py
tests/formatter/test_tox_section.py
tests/test_main.py
tests/test_upgrade.py

Upgrade configuration syntax to v4

---

.pre-commit-config.yaml
pyproject.toml
setup.cfg

Committed via https://github.com/asottile/all-repos

Bump deps and tools

---

.github/workflows/check.yml
.pre-commit-config.yaml
src/tox_ini_fmt/cli.py

Fix type checker

---

.github/workflows/check.yml
.github/workflows/release.yml
.pre-commit-config.yaml
src/tox_ini_fmt/formatter/util.py
tests/formatter/test_tox_section.py
tox.ini

Support dot version environment names for env_list ordering
